### PR TITLE
[t-mr1] vendor: etc: acdbdata: Remove acdb_cal.acdb

### PR DESCRIPTION
**Pull request by bartcubbins**
This file is not part of ACDB for this device and crashes the entire audio subsystem due to invalid data.

Valid list of calibration files and their MD5 checksums according to 68.0.A.0.768 stock firmware:
```
3b17b4c5bf5a7b719edc02e04eca1a35  adsp_avs_config.acdb
6149eaa375c7a493bcb2b6a548db2335  Bluetooth_cal.acdb
e0843c4ede5472bd24cf8f2b5c9570df  General_cal.acdb
496f526a91147cbd07d142be4921f95a  Global_cal.acdb
649da9a5079ec76a6b691841a682dd79  Handset_cal.acdb
f3553f5750541c46041910053219cd5d  Hdmi_cal.acdb
72ec2ed93d1a3b314e158e82c6cd9675  Headset_cal.acdb
2ad9c731b70fc1785b03a4e8a0435926  Speaker_cal.acdb
2fa3a26d8b3e00f39f3d5e36854115a4  workspaceFile.qwsp
da36448ca9b8a84adb241ab00669ae35  nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd
51df16b39e6a602e7fa92b4a770693c1  nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd
87aebffabf1ff9601a5ab6d0d5a99eb1  nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__eai_1.10_enpu1.pmd
93692007d8fecee8c3c63bca5c7b90b8  nn_ns_models/fai__2.7.8_0.0__eai_1.10.pmd
9bd8c84f7c2944ea8355c94a19e8fcc2  nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__eai_1.10.pmd
06829781ebb52002ed4c78d8e386c1e7  nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd
```

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]
Looks like the other files already contain what we need then :)

**Comment by bartcubbins** [comment]
You are right. acdb_cal.acdb is an amalgamation of all calibration files. originally owned by the Nagara platform
https://github.com/sonyxperiadev/device-sony-pdx223/tree/master/rootdir/vendor/etc/acdbdata
https://github.com/sonyxperiadev/device-sony-pdx224/tree/master/rootdir/vendor/etc/acdbdata

**Comment by bartcubbins** [comment]
[pavel@home-pc sony]$ md5sum pdx224/rootdir/vendor/etc/acdbdata/acdb_cal.acdb 
35e21cee1466e93eabab52c1c1bcb025  pdx224/rootdir/vendor/etc/acdbdata/acdb_cal.acdb
[pavel@home-pc sony]$ md5sum pdx235/rootdir/vendor/etc/acdbdata/acdb_cal.acdb 
35e21cee1466e93eabab52c1c1bcb025  pdx235/rootdir/vendor/etc/acdbdata/acdb_cal.acdb

**Comment by MarijnS95** [comment]
That's not good... Looks like a remnant from enabling the new platforms by copying the old... And pasting downstream files over it without first removing the old?

**Comment by bartcubbins** [comment]
Yes. It was cool to have something like a template repository for a quick bringup

**Comment by MarijnS95** [comment]
Sometimes I wonder if, when we have to copy this much of base/boilerplate, should/could more of it be moved out to the common repos so that these can be built from scratch more easily without such remnants? We always find a thing or two.

**Comment by jerpelea** [comment]
we moved as much as possible to the common but we can always evaluate and clean if possible

**Pull request merged**
